### ISSUE TITLE
braveblock does not support apple m1/m2

### ISSUE THREAD

**Issue by cxb811201** [emacs-eaf/eaf-browser#52]
braveblock does not support apple m1/m2

**Comment by cxb811201** [comment]
Traceback (most recent call last):
  File "/Users/xianbin/.doom.d/site-lisp/eaf/core/utils.py", line 52, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/xianbin/.doom.d/site-lisp/eaf/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/xianbin/.doom.d/site-lisp/eaf/eaf.py", line 170, in create_buffer
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/xianbin/.doom.d/site-lisp/eaf/app/browser/buffer.py", line 32, in <module>
    import braveblock
ModuleNotFoundError: No module named 'braveblock'

**Comment by manateelazycat** [comment]
已经更新了， 如果 braveblock 没法用也不影响正常浏览器上网， 只是没有广告过滤功能。

目前没有找到比 braveblock 性能更好的正则匹配库， 用性能较低的库， 广告过滤会影响浏览器上网性能。
