### ISSUE TITLE
[leetcode.cn] Ooops, page crashed

### ISSUE THREAD

**Issue by ententent** [emacs-eaf/eaf-browser#60]
使用 eaf-browser 打开 leetcode.cn，Vimium 快捷键跳转的很舒服

直到最后一步，点进具体的某个题目后，就会报错

```
Ooops, page crashed
Crash ID: 1bd53292
```

OS: Arch Linux

**Comment by manateelazycat** [comment]
```
_app-146634da90b992a6.js:1 RangeError: Invalid array length
    at Ie ([slug]-abaee426f4d298e1.js:1:34157)
    at [slug]-abaee426f4d298e1.js:1:39547
    at [slug]-abaee426f4d298e1.js:1:39721
    at [slug]-abaee426f4d298e1.js:1:40501
    at Object.useMemo (framework-9229be13098fd6ad.js:1:69564)
    at n.useMemo (framework-9229be13098fd6ad.js:1:136652)
    at it ([slug]-abaee426f4d298e1.js:1:40447)
    at wn ([slug]-abaee426f4d298e1.js:1:73434)
    at Eo (framework-9229be13098fd6ad.js:1:63196)
    at xi (framework-9229be13098fd6ad.js:1:120436)
    at bs (framework-9229be13098fd6ad.js:1:109372)
    at gs (framework-9229be13098fd6ad.js:1:109300)
    at vs (framework-9229be13098fd6ad.js:1:109163)
    at as (framework-9229be13098fd6ad.js:1:105943)
    at ls (framework-9229be13098fd6ad.js:1:104494)
    at S (framework-9229be13098fd6ad.js:1:138468)
    at MessagePort.T (framework-9229be13098fd6ad.js:1:139002)
(anonymous) @ _app-146634da90b992a6.js:1
du @ framework-9229be13098fd6ad.js:1
a.componentDidCatch.t.callback @ framework-9229be13098fd6ad.js:1
Ua @ framework-9229be13098fd6ad.js:1
ki @ framework-9229be13098fd6ad.js:1
bi @ framework-9229be13098fd6ad.js:1
yi @ framework-9229be13098fd6ad.js:1
(anonymous) @ framework-9229be13098fd6ad.js:1
ws @ framework-9229be13098fd6ad.js:1
ls @ framework-9229be13098fd6ad.js:1
S @ framework-9229be13098fd6ad.js:1
T @ framework-9229be13098fd6ad.js:1
framework-9229be13098fd6ad.js:1 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xi (framework-9229be13098fd6ad.js:1:121816)
    at bs (framework-9229be13098fd6ad.js:1:109372)
    at gs (framework-9229be13098fd6ad.js:1:109300)
    at vs (framework-9229be13098fd6ad.js:1:109163)
    at as (framework-9229be13098fd6ad.js:1:105943)
    at ls (framework-9229be13098fd6ad.js:1:104494)
    at S (framework-9229be13098fd6ad.js:1:138468)
    at MessagePort.T (framework-9229be13098fd6ad.js:1:139002)
xi @ framework-9229be13098fd6ad.js:1
bs @ framework-9229be13098fd6ad.js:1
gs @ framework-9229be13098fd6ad.js:1
vs @ framework-9229be13098fd6ad.js:1
as @ framework-9229be13098fd6ad.js:1
ls @ framework-9229be13098fd6ad.js:1
S @ framework-9229be13098fd6ad.js:1
T @ framework-9229be13098fd6ad.js:1
VM441:2708 Canvas2
```

出错页面按 F12 可以知道网页具体的报错， 我Chrome试了没问题， 估计是 leetcode.cn 这个团队的前端代码写的不够健壮吧， 去报给 leetcode 团队吧。

JavaScript 的前端代码不会把浏览器搞崩溃的， 前端页面自己崩溃以后应该报错误给对应的网站。
